Microsoft Windows [Version 10.0.17763.1757]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\yle4>cd code/az-covid

C:\Users\yle4\code\az-covid>python combo_dev.py
0
17632632
Process SpawnPoolWorker-26:
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\multiprocessing\pool.py", line 125, in worker
    put((job, i, result))
  File "C:\Program Files\Python36\lib\multiprocessing\queues.py", line 341, in put
    obj = _ForkingPickler.dumps(obj)
  File "C:\Program Files\Python36\lib\multiprocessing\reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Program Files\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python36\lib\multiprocessing\pool.py", line 127, in worker
    wrapped = MaybeEncodingError(e, result[1])
  File "C:\Program Files\Python36\lib\multiprocessing\pool.py", line 82, in __init__
    self.value = repr(value)
MemoryError
Process SpawnPoolWorker-36:
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\multiprocessing\pool.py", line 125, in worker
    put((job, i, result))
  File "C:\Program Files\Python36\lib\multiprocessing\queues.py", line 341, in put
    obj = _ForkingPickler.dumps(obj)
  File "C:\Program Files\Python36\lib\multiprocessing\reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Program Files\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python36\lib\multiprocessing\pool.py", line 127, in worker
    wrapped = MaybeEncodingError(e, result[1])
  File "C:\Program Files\Python36\lib\multiprocessing\pool.py", line 82, in __init__
    self.value = repr(value)
MemoryError
Process SpawnPoolWorker-42:
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\multiprocessing\pool.py", line 125, in worker
    put((job, i, result))
  File "C:\Program Files\Python36\lib\multiprocessing\queues.py", line 341, in put
    obj = _ForkingPickler.dumps(obj)
  File "C:\Program Files\Python36\lib\multiprocessing\reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Program Files\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python36\lib\multiprocessing\pool.py", line 127, in worker
    wrapped = MaybeEncodingError(e, result[1])
  File "C:\Program Files\Python36\lib\multiprocessing\pool.py", line 82, in __init__
    self.value = repr(value)
MemoryError
